version: '3'
services:
    app:
        build: 
            context: .
            dockerfile: build/Dockerfile_python
        volumes:
            - ./app:/usr/src/app
        expose:
            - "3000"
        environment:
            - APP_ENV=development
            - NODE_VERSION=${NODE_VERSION}
            - YARN_VERSION=${YARN_VERSION}
            - HOST=${HOST}
            - PORT=${PORT}
    nginx:
        build:
            context: .
            dockerfile: build/Dockerfile_nginx
        volumes:
            - ./app:/var/www
            - ./logs/nginx:/var/log/nginx
            - ./config/nginx/sites:/etc/nginx/sites-available
        ports:
            - 80:80
        depends_on:
            - app

volumes:
    socketvol: {}
